$(document).ready(function () {
    $("#graduation").change(function () {
        var val = $(this).val();
        if (val == "ug") {
            $("#specification").html("<option value='BBA- Bachelor of Business Administration'>BBA- Bachelor of Business Administration</option><option value='BMS- Bachelor of Management Science'>BMS- Bachelor of Management Science</option><option value='BFA- Bachelor of Fine Arts'>BFA- Bachelor of Fine Arts</option><option value='BEM- Bachelor of Event Management'>BEM- Bachelor of Event Management</option><option value='Integrated Law Course- BA + LL.B'>Integrated Law Course- BA + LL.B</option><option value='BJMC- Bachelor of Journalism and Mass Communication'>BJMC- Bachelor of Journalism and Mass Communicatio></option><option value='BFD- Bachelor of Fashion Designing'>BFD- Bachelor of Fashion Designing</option><option value='BSW- Bachelor of Social Work'>BSW- Bachelor of Social Work</option><option value='BTTM- Bachelor of Travel and Tourism Management'>BTTM- Bachelor of Travel and Tourism Management</option><option value='Aviation Courses'>Aviation Courses</option><option value='B.Sc- Interior Design'>B.Sc- Interior Design</option><option value='B.Sc.- Hospitality and Hotel Administration'>B.Sc.- Hospitality and Hotel Administration</option><option value='Bachelor of Design (B. Design)'>Bachelor of Design (B. Design)</option><option value='Bachelor of Performing Arts'>Bachelor of Performing Arts</option><option value='BA in History'>BA in History</option><option value='BE/B.Tech- Bachelor of Technology'>BE/B.Tech- Bachelor of Technology</option><option value='B.Arch- Bachelor of Architecture'>B.Arch- Bachelor of Architecture</option><option value='BCA- Bachelor of Computer Applications'>BCA- Bachelor of Computer Applications</option><option value='B.Sc.- Information Technology'>B.Sc.- Information Technology</option><option value='B.Sc- Nursing'>B.Sc- Nursing</option><option value='BPharma- Bachelor of Pharmacy'>BPharma- Bachelor of Pharmacy</option><option value='B.Sc- Interior Design'>B.Sc- Interior Design</option><option value='BDS- Bachelor of Dental Surgery'>BDS- Bachelor of Dental Surgery</option><option value='Animation, Graphics and Multimedia'>Animation, Graphics and Multimedia</option><option value='B.Sc. – Nutrition & Dietetics'>B.Sc. – Nutrition & Dietetics</option><option value='BPT- Bachelor of Physiotherapy'>BPT- Bachelor of Physiotherapy</option><option value='B.Sc- Applied Geology'>B.Sc- Applied Geology</option>");
        } else if (val == "pg") {
            $("#specification").html("<option value='BBA- Bachelor of Business Administration'>BBA- Bachelor of Business Administration</option><option value='BMS- Bachelor of Management Science'>BMS- Bachelor of Management Science</option><option value='BFA- Bachelor of Fine Arts'>BFA- Bachelor of Fine Arts</option><option value='BEM- Bachelor of Event Management'>BEM- Bachelor of Event Management</option><option value='Integrated Law Course- BA + LL.B'>Integrated Law Course- BA + LL.B</option><option value='BJMC- Bachelor of Journalism and Mass Communication'>BJMC- Bachelor of Journalism and Mass Communicatio></option><option value='BFD- Bachelor of Fashion Designing'>BFD- Bachelor of Fashion Designing</option><option value='BSW- Bachelor of Social Work'>BSW- Bachelor of Social Work</option><option value='BTTM- Bachelor of Travel and Tourism Management'>BTTM- Bachelor of Travel and Tourism Management</option><option value='Aviation Courses'>Aviation Courses</option><option value='B.Sc- Interior Design'>B.Sc- Interior Design</option><option value='B.Sc.- Hospitality and Hotel Administration'>B.Sc.- Hospitality and Hotel Administration</option><option value='Bachelor of Design (B. Design)'>Bachelor of Design (B. Design)</option><option value='Bachelor of Performing Arts'>Bachelor of Performing Arts</option><option value='BA in History'>BA in History</option><option value='BE/B.Tech- Bachelor of Technology'>BE/B.Tech- Bachelor of Technology</option><option value='B.Arch- Bachelor of Architecture'>B.Arch- Bachelor of Architecture</option><option value='BCA- Bachelor of Computer Applications'>BCA- Bachelor of Computer Applications</option><option value='B.Sc.- Information Technology'>B.Sc.- Information Technology</option><option value='B.Sc- Nursing'>B.Sc- Nursing</option><option value='BPharma- Bachelor of Pharmacy'>BPharma- Bachelor of Pharmacy</option><option value='B.Sc- Interior Design'>B.Sc- Interior Design</option><option value='BDS- Bachelor of Dental Surgery'>BDS- Bachelor of Dental Surgery</option><option value='Animation, Graphics and Multimedia'>Animation, Graphics and Multimedia</option><option value='B.Sc. – Nutrition & Dietetics'>B.Sc. – Nutrition & Dietetics</option><option value='BPT- Bachelor of Physiotherapy'>BPT- Bachelor of Physiotherapy</option><option value='B.Sc- Applied Geology'>B.Sc- Applied Geology</option>");
        } 
    });
});


$(document).ready(function () {
    $("#developer-type").change(function () {
        var val1 = $(this).val();
        if (val1 == "webdev") {
            $("#skillset").html("<option value=''>Select</option><option value='mern'>Mern Stack</option><option value='mean'>Mean Stack</option><option value='lamp'>Lamp Stack</option><option value='asp'>Asp.net</option><option value='java'>JAVA</option><option value='python'>Python</option><option value='php'>PHP</option>");
        } else if (val1 == "mobiledev") {
            $("#skillset").html("<option value=''>Select</option><option value='hybrid_app'>Hybrid App</option><option value='flutter'>Flutter</option>");
        } else if (val1 == "uidev") {
            $("#skillset").html("<option value=ui_dev''>Ui Developer</option>");
        } 
    });
});


